config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'sign_in', to: 'sessions#new', as: 'sign_in'
    post 'sign_in', to: 'sessions#create'
    get 'sign_out', to: 'sessions#destroy'
    get 'landing', to: 'pages#landing', as: 'landing'
  
    resources :projects, only: [:index, :new, :create, :show, :edit, :update] do
      resources :tasks
    end
    resources :resources, only: [:index, :new, :create, :show, :edit, :update] 
    resources :assignments, only: [:new, :create, :show, :edit, :update]
    resources :users, only: [:index, :new, :create, :show, :edit, :update]
    resources :translations, only: [:index, :create]
    root to: 'home#index'
 end
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :resource
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base 
  has_many :tasks, dependent: :destroy  
  
  has_many :assignments
  has_many :resources, through: :assignments
  
  validates :name, presence: true
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  has_many :assignments
  has_many :projects, through: :assignments
  
  validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  
  validates :name, presence: true
  validates :due_date, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, email: true
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authorize
  before_action :set_locale
  
  def default_url_options(options = {})
    {locale: I18n.locale}
  end
  
  private
    def current_user
      warden.user
    end
    helper_method :current_user
    
    def authorize
      redirect_to sign_in_url, alert: "You must be signed in to do that!" if current_user.nil?
    end
    
    def warden
      env['warden']
    end
    
    def set_locale
      I18n.locale = params[:locale] if params[:locale].present?
    end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :find_assignment, only: [:edit, :update, :show]
  
  def new
    @assignment = Assignment.new
  end
  
  def create
     @assignment = Assignment.new(assignment_params)
    if @assignment.save
      redirect_to @assignment, notice: 'Assignment successfully created.'
    else
      flash.now[:alert] = 'Assignment was not created.'
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @assignment.update(assignment_params)
      redirect_to assignment_path(@assignment), notice: 'Assignment successfully updated.'
    else
      flash.now[:alert] = 'Assignment was not saved.'
      render :edit
    end
  end
  
  private
    def find_assignment
      @assignment = Assignment.find(params[:id])
    end
    
    def assignment_params
      params.require(:assignment).permit(:project_id, :resource_id, :start_date, :end_date)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authorize, only: [:landing]
  
  def landing 
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :update, :edit]
  
  def index
    @projects = Project.all
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(project_params)
      if @project.save
        redirect_to @project, notice: "Project successfully created"
      else
        render :new
      end
  end
  
  def show
    @tasks = @project.tasks.all
    @resources = @project.resources.all
  end
  
  def edit
  end
  
  def update
    if @project.update(project_params)
      redirect_to @project, notice: "Project successfully updated"
    else
      render :edit
    end
  end
  
  
  private
    def find_project
      @project = Project.find(params[:id])
    end
  
    def project_params
      params.require(:project).permit(:name, :description, :start_date, :projected_end_date, :actual_end_date, :budget, :cost)
    end
    
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController 
  before_action :find_resource, only: [:show, :edit, :update]
  
  def index
    @resources = Resource.all
  end
  
  def new
    @resource = Resource.new
  end
  
  def create
    @resource = Resource.new(resource_params)
      if @resource.save
        redirect_to @resource, notice: "Resource successfully created"
      else
        flash.now[:alert] = "Resource not saved"
        render :new
      end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @resource.update(resource_params)
      redirect_to @resource, notice: "Successfully updated resource name"
    else
      flash.now[:alert] = "Your resource was not updated"
      render :edit
    end
  end
  
  private
    def resource_params
      params.require(:resource).permit(:name, :description)
    end
  
    def find_resource
      @resource = Resource.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  
  def new
    flash.now[:alert] = warden.message if warden.message.present?
  end
  
  def create
    warden.authenticate!
    redirect_to root_url, notice: "You have successfully signed in!"
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to landing_path, notice: "You have been signed out of the application!"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :find_task, only: [:show, :edit, :update]
  
  def index
    @tasks = @project.tasks.all
  end
  
  def new
    @task = @project.tasks.build
  end
  
  def create
    @task = @project.tasks.build(task_params)
    
    if @task.save
      redirect_to [@project, @task], notice: 'Task Saved'
    else
      flash.now[:alert] = 'Task not saved'
      render :new
    end
  end
  
  def show
    
  end
  
  def edit
  end
  
  def update
    if @task.update(task_params)
      redirect_to project_tasks_path(@project), notice: "Task Updated."
    else
      flash.now[:alert] = "Task not saved."
      render :edit
    end
  end
  
  private
    def set_project
      @project = Project.find(params[:project_id])
    end
    
    def task_params
      params.require(:task).permit(:name, :due_date)
    end
    
    def find_task
      @task = @project.tasks.find(params[:id])
    end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  
  def index
    @translations = TRANSLATION_STORE
  end
  
  def create
    I18n.backend.store_translations(params[:locale], {params[:key] => params[:value]}, :escape => false)
    redirect_to (translations_url), notice: 'Translation added successfully.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.test_email(@user.email).deliver_later
      redirect_to @user, notice: 'User successfully created.'
    else
      flash.now[:alert] = 'User was not created.'
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User successfully updated"
    else
      flash.now[:alert] = "Oops, something went wrong. Try again"
      render 'new'
    end
  end
  
  private
    def find_user
      @user = User.find(params[:id])
    end
    
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def foundation_flash_class(level)
    case level.to_sym
      when :notice  then "callout success"
      when :alert   then "callout alert"
    end
  end
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f|%>
<%= render 'shared/errors', object: @assignment %>
  
<fieldset>
  <div class="field">
    <%= f.label :project %><br />
    <%= f.select :project_id, Project.all.collect { |p| [ p.name, p.id ] } %>
  </div>
  <div class="field">
    <%= f.label :resource %><br />
    <%= f.select :resource_id, Resource.all.collect { |p| [ p.name, p.id ] } %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.text_field :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

app/views/assignments/edit.html.erb
<h1>Edit Assignment</h1>

<%= render 'form' %>

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render 'form' %>

app/views/assignments/show.html.erb
<h1>Assignment for <%= @assignment.project.name %></h1>

<table>
  <thead>
    <tr>
      <td>Resource</td>
      <td>Start Date</td>
      <td>End Date</td>
    </tr>
    <tr>
      <td><%= @assignment.resource.name %></td>
      <td><%= @assignment.start_date %></td>
      <td><%= @assignment.end_date %></td>
    </tr>
  </thead>
</table>

app/views/layouts/_header.html.erb
<header>
  <div class="top-bar">
    <div class="top-bar-title">
      <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
        <span class="menu-icon dark" data-toggle></span>
      </span>
      <strong><%= link_to('Projectrr', root_path) %></strong>
    </div>
    <div id="responsive-menu">
      <div class="top-bar-left">
        <ul class="menu">
          <%= render 'layouts/nav_links' %>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <% if current_user %>
            Hello, <%= current_user.name %>! 
            <%= link_to('Sign Out', sign_out_path) %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="<%= foundation_flash_class(key) %>" data-closable>
      <%= value %>
    <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_nav_links.html.erb
<li><%= link_to 'Projects', projects_url %></li>
<li><%= link_to 'Resources', resources_url %></li>
<li><%= link_to 'Users', users_url %></li>
<li><%= link_to 'Sign In', sign_in_path %></li>

app/views/layouts/application.html.1.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projectrr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/messages' %>

  <%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "PROJECTRR" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    
    <%= yield %>

  </body>
</html>

app/views/pages/landing.html.erb
See ya!

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <%= render 'shared/errors', object: @project %>
  
  <fieldset>
    <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
    </div>
    <div class="field">
        <%= f.label :start_date %><br>
        <%= f.text_field :start_date %>
    </div>
    <div class="field">
        <%= f.label :projected_end_date %><br>
        <%= f.text_field :projected_end_date %>
    </div>
    <div class="field">
        <%= f.label :actual_end_date %><br>
        <%= f.text_field :actual_end_date %>
    </div>
    <div class="field">
        <%= f.label :budget %><br>
        <%= f.text_field :budget %>
    </div>
    <div class="field">
        <%= f.label :cost %><br>
        <%= f.text_field :cost %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
  </fieldset>
  
<% end %>

app/views/projects/edit.html.erb
<h1>Edit <%= @project.name %></h1>
  
 <%= render 'form' %>

 

app/views/projects/index.html.erb
<div class="button-group">
  <%= link_to_unless_current("English", {locale: 'en'}, {class: 'button'}) %>
  <%= link_to_unless_current("German", {locale: 'de'}, {class: 'button'}) %>
  <%= link_to_unless_current("Spanish", {locale: 'es'}, {class: 'button'}) %>
</div>

<h1><%= t('.title') %> </h1>

<%= "#{pluralize(@projects.count, "project")} #{t('.subtitle')}" %>

<table id="projects">
  <thead>
    <tr>
      <td><%= Project.human_attribute_name(:name) %></td>
      <td><%= Project.human_attribute_name(:description) %></td>
      <td><%= Project.human_attribute_name(:start_date) %></td>
      <td><%= Project.human_attribute_name(:projected_end_date) %></td>
      <td><%= Project.human_attribute_name(:actual_end_date) %></td>
      <td><%= Project.human_attribute_name(:budget) %></td>
      <td><%= Project.human_attribute_name(:cost) %></td>
      <td><%= t('.action') %></td>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.start_date.to_formatted_s(:long) %></td>
        <td><%= project.projected_end_date.to_formatted_s(:long) %></td>
        <td><%= project.actual_end_date.to_formatted_s(:long) %></td>
        <td><%= number_to_currency(project.budget) %></td>
        <td><%= number_to_currency(project.cost) %></td>
        <td><a href="projects-show.html"><%= link_to(project.name, project) %></a></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to('New Project', new_project_path) %>

app/views/projects/new.html.erb
<h1>New Project</h1>
  
  <div class="field">
    <%= render 'form' %>
  </div>
  

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<h2><%= @project.description %></h2>

<p><%= @project.start_date %></p>
<p><%= @project.projected_end_date %></p>
<p><%= @project.actual_end_date %></p>
<p><%= @project.budget %></p>
<p><%= @project.cost %></p>

<p><%= link_to('Edit Project', edit_project_path(@project)) %></p>
<p><%= link_to('Add Task', new_project_task_path(@project)) %></p>

<article>
  <header>
    <h2>Tasks</h2>
    <table>
      <thead>
        <tr>
          <td>Name</td>
          <td>Due Date</td>
          <td>Action</td>
        </tr>
      </thead>
      <tbody>
        <% @project.tasks.each do |task| %>
        <tr>
          <td><%= task.name %></td>
          <td><%= task.due_date %></td>
          <td><%= link_to('Edit Task', edit_project_task_path(@project, task)) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </header>
</article>

<article>
  <header>
    <h2>Resource</h2>
    <table>
      <thead>
        <tr>
          <td>Name</td>
          <td>Description</td>
        </tr>
      </thead>
      <tbody>
        <%= @resources.all.each do |resource| %>
          <tr>
            <td><%= resource.name %></td>
            <td><%= resource.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </header>
</article>

app/views/resources/_form.html.erb
<%= form_for @resource do |f| %>
  <%= render 'shared/errors', object: @resource %>
  <fieldset>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/resources/edit.html.erb
<h1>Edit Resource</h1>

<%= render 'form' %>

app/views/resources/index.html.erb
<%= "#{pluralize(@resources.count, "resource")}" %>

<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Description</td>
    </tr>
  </thead>
  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= resource.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to('New Resource', new_resource_path) %> 

app/views/resources/new.html.erb
<h1>Create Resource</h1>

<%= render 'form' %>

app/views/resources/show.html.erb
<h1><%= @resource.name %></h1>
<h2><%= @resource.description %></h2>

<%= link_to('Edit Resource', edit_resource_path(@resource)) %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<div id='error_explanation'>
  <h2><%= pluralize(object.errors.count, 'error') %> prohibited this <%= object.class.name.humanize.downcase %> from being saved:</h2>

  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/tasks/_form.html.erb
<%= render 'shared/errors', object: @task %>
<%= form_for([@project, @task]) do |f| %>
  <fieldset>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :due_date %><br>
      <%= f.text_field :due_date %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>

<% end %>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.name %></h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks for <%= @project.name %> </h1>

<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Due Date</td>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.due_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<h1>Add a task to <%= @project.name %></h1>

<%= form_for([@project, @task]) do |f| %>
    <fieldset>
        <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
        </div>
        <div class="field">
            <%= f.label :due_date %><br>
            <%= f.text_field :due_date %>
        </div>
        <div class="actions">
            <%= f.submit %>
        </div>
    </fieldset>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @project.name %></h1>

<h2><%= @task.name %></h2>

<p><%= @task.due_date %></p>

app/views/translations/index.html.erb
<h1>Translations</h1>

  <ul>
    <% @translations.keys.each do |key| %>
      <li><%= key %>: <%= @translations[key] %></li>
    <% end %>
  </ul>
  
  <h2>Add Translation</h2>
  <%= form_tag translations_path do %>
  <p>
   <%= label_tag :locale %><br />
   <%= text_field_tag :locale %>
  </p>
  <p>
    <%= label_tag :key %><br />
    <%= text_field_tag :key %>
  </p>
  <p>
    <%= label_tag :value %><br />
    <%= text_field_tag :value %>
  </p>
  <p><%= submit_tag "Submit" %></p>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render 'shared/errors', object: @user %>
  <fieldset>
    <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :email %><br>
        <%= f.email_field :email %>
    </div>
    <div class="field">
        <%= f.label :password %><br>
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<%= "#{pluralize(@users.count, "user")}" %>

<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Email</td>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to('New User', new_user_path) %></p>

app/views/users/new.html.erb
<h1>Create a user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= @user.email %></p>

<p><%= link_to('Edit User', edit_user_path) %></p>